INFO 2025-10-10 17:12:47,217 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:12:49,961 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:13:19,210 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:13:19,549 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:13:24,745 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:13:25,150 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:13:33,937 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:13:33,972 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:13:39,725 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:13:41,112 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:13:48,390 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\core\logging_handlers.py changed, reloading.
INFO 2025-10-10 17:13:48,692 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\core\logging_handlers.py changed, reloading.
INFO 2025-10-10 17:13:53,189 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:13:54,406 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:14:33,067 __main__ test_login_fix test_authentication 31 Test log message with Unicode: ✓ ✗ ★ ♥
WARNING 2025-10-10 17:14:36,142 accounts.backends backends authenticate 41 App authentication failed: Incorrect password for 08032194090
INFO 2025-10-10 17:19:52,703 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\forms.py changed, reloading.
INFO 2025-10-10 17:19:53,018 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\forms.py changed, reloading.
INFO 2025-10-10 17:19:57,154 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:19:57,340 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:20:51,725 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\forms.py changed, reloading.
INFO 2025-10-10 17:20:52,019 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\forms.py changed, reloading.
INFO 2025-10-10 17:20:55,001 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:20:55,015 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:21:14,398 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py changed, reloading.
INFO 2025-10-10 17:21:14,777 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py changed, reloading.
INFO 2025-10-10 17:21:17,901 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:21:18,486 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:25:45,077 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:27:09,105 __main__ test_login_fix test_authentication 31 Test log message with Unicode: ✓ ✗ ★ ♥
WARNING 2025-10-10 17:27:11,301 accounts.backends backends authenticate 41 App authentication failed: Incorrect password for 08032194090
INFO 2025-10-10 17:27:59,852 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:30:42,588 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\manage.py changed, reloading.
INFO 2025-10-10 17:30:42,600 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\manage.py changed, reloading.
INFO 2025-10-10 17:30:45,686 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:30:45,909 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:31:18,135 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:31:18,820 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:31:21,221 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:31:22,882 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:31:35,034 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:31:35,068 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:31:40,785 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:31:41,016 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:34:04,147 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:34:04,397 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-10 17:34:07,661 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:42:28,010 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-10 17:43:18,588 django.server basehttp log_message 213 "GET / HTTP/1.1" 200 31713
WARNING 2025-10-10 17:43:19,024 django.request log log_response 253 Not Found: /favicon.ico
WARNING 2025-10-10 17:43:19,025 django.server basehttp log_message 213 "GET /favicon.ico HTTP/1.1" 404 7109
INFO 2025-10-10 17:43:20,908 django.server basehttp log_message 213 "GET /accounts/login/ HTTP/1.1" 200 30083
INFO 2025-10-10 17:43:27,817 django.server basehttp log_message 213 "POST /accounts/login/ HTTP/1.1" 302 0
INFO 2025-10-10 17:43:28,039 django.server basehttp log_message 213 "GET /dashboard/ HTTP/1.1" 200 86372
INFO 2025-10-10 17:43:28,439 django.server basehttp log_message 213 "GET /media/profile_pics/passport_1a-285x370_Le7spvx.jpg HTTP/1.1" 200 25304
INFO 2025-10-11 14:28:44,485 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:30:20,169 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:32:58,988 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\pharmacy\urls.py changed, reloading.
INFO 2025-10-11 14:33:01,360 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:34:04,379 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\pharmacy\urls.py changed, reloading.
INFO 2025-10-11 14:34:06,337 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:34:48,883 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:38:32,332 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:45:53,904 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
WARNING 2025-10-11 14:46:19,864 django.request log log_response 248 Not Found: /favicon.ico
WARNING 2025-10-11 14:46:19,865 django.server basehttp log_message 213 "GET /favicon.ico HTTP/1.1" 404 7109
INFO 2025-10-11 14:46:41,205 django.server basehttp log_message 213 "GET / HTTP/1.1" 200 31713
INFO 2025-10-11 14:46:42,164 django.server basehttp log_message 213 "GET /static/css/style_new.css HTTP/1.1" 200 25846
INFO 2025-10-11 14:46:42,212 django.server basehttp log_message 213 "GET /static/css/patient_search.css HTTP/1.1" 200 5195
INFO 2025-10-11 14:46:42,270 django.server basehttp log_message 213 "GET /static/js/sidebar.js HTTP/1.1" 200 3073
WARNING 2025-10-11 14:46:42,622 django.request log log_response 248 Not Found: /favicon.ico
WARNING 2025-10-11 14:46:42,623 django.server basehttp log_message 213 "GET /favicon.ico HTTP/1.1" 404 7109
INFO 2025-10-11 14:47:08,300 django.server basehttp log_message 213 "GET / HTTP/1.1" 200 31713
INFO 2025-10-11 14:47:08,408 django.server basehttp log_message 213 "GET /static/css/style_new.css HTTP/1.1" 200 25846
INFO 2025-10-11 14:47:08,505 django.server basehttp log_message 213 "GET /static/css/patient_search.css HTTP/1.1" 200 5195
INFO 2025-10-11 14:47:08,563 django.server basehttp log_message 213 "GET /static/js/sidebar.js HTTP/1.1" 200 3073
INFO 2025-10-11 14:47:13,522 django.server basehttp log_message 213 "GET / HTTP/1.1" 200 31713
INFO 2025-10-11 14:47:20,525 django.server basehttp log_message 213 "GET /accounts/login/ HTTP/1.1" 200 30083
INFO 2025-10-11 14:47:31,478 django.server basehttp log_message 213 "POST /accounts/login/ HTTP/1.1" 302 0
INFO 2025-10-11 14:47:31,848 django.server basehttp log_message 213 "GET /dashboard/ HTTP/1.1" 200 86372
INFO 2025-10-11 14:47:31,935 django.server basehttp log_message 213 "GET /media/profile_pics/passport_1a-285x370_Le7spvx.jpg HTTP/1.1" 200 25304
INFO 2025-10-11 14:49:08,620 django.server basehttp log_message 213 "GET /pharmacy/transfers/inter/ HTTP/1.1" 200 76279
INFO 2025-10-11 14:49:43,089 django.server basehttp log_message 213 "GET /pharmacy/transfers/inter/create/ HTTP/1.1" 200 88121
INFO 2025-10-11 14:50:04,223 django.server basehttp log_message 213 "GET /accounts/user-dashboard/ HTTP/1.1" 200 114797
ERROR 2025-10-11 14:50:20,477 django.request log log_response 248 Internal Server Error: /accounts/role-demo/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py", line 1342, in role_demo
    roles = Role.objects.annotate(
            ~~~~~~~~~~~~~~~~~~~~~^
        user_count=Count('customuser_roles')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).prefetch_related('permissions', 'customuser_roles__profile')
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1635, in annotate
    return self._annotate(args, kwargs, select=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1687, in _annotate
    clone.query.add_annotation(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        annotation,
        ^^^^^^^^^^^
        alias,
        ^^^^^^
        select=select,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1218, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\aggregates.py", line 181, in resolve_expression
    result = super().resolve_expression(*args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\expressions.py", line 300, in resolve_expression
    expr.resolve_expression(query, allow_joins, reuse, summarize)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\expressions.py", line 902, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 2046, in resolve_ref
    join_info = self.setup_joins(
        field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse
    )
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1897, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ~~~~~~~~~~~~~~~~~~^
        names[:pivot],
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        fail_on_missing=True,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'customuser_roles' into field. Choices are: children, customuser_role, description, id, name, parent, parent_id, permissions
ERROR 2025-10-11 14:50:20,494 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 500 151299
INFO 2025-10-11 14:50:31,843 django.server basehttp log_message 213 "GET /accounts/roles/ HTTP/1.1" 200 88545
ERROR 2025-10-11 14:50:40,677 django.request log log_response 248 Internal Server Error: /accounts/role-demo/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py", line 1342, in role_demo
    roles = Role.objects.annotate(
            ~~~~~~~~~~~~~~~~~~~~~^
        user_count=Count('customuser_roles')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).prefetch_related('permissions', 'customuser_roles__profile')
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1635, in annotate
    return self._annotate(args, kwargs, select=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1687, in _annotate
    clone.query.add_annotation(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        annotation,
        ^^^^^^^^^^^
        alias,
        ^^^^^^
        select=select,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1218, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\aggregates.py", line 181, in resolve_expression
    result = super().resolve_expression(*args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\expressions.py", line 300, in resolve_expression
    expr.resolve_expression(query, allow_joins, reuse, summarize)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\expressions.py", line 902, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 2046, in resolve_ref
    join_info = self.setup_joins(
        field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse
    )
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1897, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ~~~~~~~~~~~~~~~~~~^
        names[:pivot],
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        fail_on_missing=True,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'customuser_roles' into field. Choices are: children, customuser_role, description, id, name, parent, parent_id, permissions
ERROR 2025-10-11 14:50:40,681 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 500 151299
INFO 2025-10-11 14:52:34,390 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py changed, reloading.
INFO 2025-10-11 14:52:37,201 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:52:41,846 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py changed, reloading.
INFO 2025-10-11 14:52:44,257 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
ERROR 2025-10-11 14:53:00,507 django.request log log_response 248 Internal Server Error: /accounts/role-demo/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py", line 1348, in role_demo
    for role in roles:
                ^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1937, in _fetch_all
    self._prefetch_related_objects()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1325, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 2358, in prefetch_related_objects
    raise AttributeError(
    ...<7 lines>...
    )
AttributeError: Cannot find 'customuser_role' on Role object, 'customuser_role__profile' is an invalid parameter to prefetch_related()
ERROR 2025-10-11 14:53:00,521 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 500 122832
INFO 2025-10-11 14:53:25,281 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py changed, reloading.
INFO 2025-10-11 14:53:31,749 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
ERROR 2025-10-11 14:53:39,366 django.request log log_response 248 Internal Server Error: /accounts/role-demo/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py", line 1342, in role_demo
    roles = Role.objects.annotate(
            ~~~~~~~~~~~~~~~~~~~~~^
        user_count=Count('customuser_roles')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).prefetch_related('permissions')
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1635, in annotate
    return self._annotate(args, kwargs, select=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1687, in _annotate
    clone.query.add_annotation(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        annotation,
        ^^^^^^^^^^^
        alias,
        ^^^^^^
        select=select,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1218, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\aggregates.py", line 181, in resolve_expression
    result = super().resolve_expression(*args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\expressions.py", line 300, in resolve_expression
    expr.resolve_expression(query, allow_joins, reuse, summarize)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\expressions.py", line 902, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 2046, in resolve_ref
    join_info = self.setup_joins(
        field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse
    )
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1897, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ~~~~~~~~~~~~~~~~~~^
        names[:pivot],
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        fail_on_missing=True,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'customuser_roles' into field. Choices are: children, customuser_role, description, id, name, parent, parent_id, permissions
ERROR 2025-10-11 14:53:39,376 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 500 151397
INFO 2025-10-11 14:54:12,607 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\views.py changed, reloading.
INFO 2025-10-11 14:54:14,881 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 14:54:29,037 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 200 111426
INFO 2025-10-11 14:54:46,198 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-11 14:54:46,279 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
INFO 2025-10-11 14:55:17,738 django.server basehttp log_message 213 "GET /accounts/users/2/privileges/ HTTP/1.1" 200 101125
INFO 2025-10-11 14:57:15,573 django.server basehttp log_message 213 "GET /accounts/users/7/privileges/ HTTP/1.1" 200 108455
INFO 2025-10-11 14:57:43,413 django.server basehttp log_message 213 "GET /accounts/users/2/privileges/ HTTP/1.1" 200 101125
INFO 2025-10-11 14:57:59,934 django.server basehttp log_message 213 "GET /accounts/users/7/privileges/ HTTP/1.1" 200 108455
INFO 2025-10-11 14:59:53,593 django.server basehttp log_message 213 "GET /accounts/users/8/privileges/ HTTP/1.1" 200 103921
INFO 2025-10-11 15:00:33,419 django.server basehttp log_message 213 "GET /accounts/users/9/privileges/ HTTP/1.1" 200 111935
INFO 2025-10-11 15:01:36,775 django.server basehttp log_message 213 "GET /accounts/users/12/privileges/ HTTP/1.1" 200 110749
INFO 2025-10-11 15:05:07,351 django.server basehttp log_message 213 "GET /accounts/roles/8/edit/ HTTP/1.1" 200 805136
INFO 2025-10-11 15:05:52,353 django.server basehttp log_message 213 "GET /dashboard/ HTTP/1.1" 200 85905
INFO 2025-10-11 15:06:48,679 django.server basehttp log_message 213 "GET /accounts/user-dashboard/ HTTP/1.1" 200 114797
INFO 2025-10-11 15:10:38,606 django.server basehttp log_message 213 "GET /accounts/roles/ HTTP/1.1" 200 88545
INFO 2025-10-11 15:12:26,614 django.server basehttp log_message 213 "GET /accounts/roles/create/ HTTP/1.1" 200 762255
INFO 2025-10-11 15:13:31,212 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-11 15:13:31,233 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
INFO 2025-10-11 15:21:43,677 django.server basehttp log_message 213 "GET /accounts/roles/ HTTP/1.1" 200 91266
INFO 2025-10-11 15:21:57,455 django.server basehttp log_message 213 "GET /accounts/roles/11/edit/ HTTP/1.1" 200 804813
INFO 2025-10-11 15:22:30,400 django.server basehttp log_message 213 "GET /accounts/roles/ HTTP/1.1" 200 91266
INFO 2025-10-11 15:22:36,640 django.server basehttp log_message 213 "GET /accounts/permissions/ HTTP/1.1" 200 702960
INFO 2025-10-11 15:22:52,495 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 200 115379
INFO 2025-10-11 15:23:23,042 django.server basehttp log_message 213 "GET /accounts/users/134/privileges/ HTTP/1.1" 200 110569
INFO 2025-10-11 15:25:40,204 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-11 15:25:40,220 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
INFO 2025-10-11 15:26:51,726 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\models.py changed, reloading.
INFO 2025-10-11 15:26:54,785 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 15:29:07,117 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\urls.py changed, reloading.
INFO 2025-10-11 15:29:10,843 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 15:34:26,270 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\models.py changed, reloading.
INFO 2025-10-11 15:34:28,280 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 15:34:42,815 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\hms\settings.py changed, reloading.
INFO 2025-10-11 15:34:44,780 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 15:44:03,490 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\models.py changed, reloading.
INFO 2025-10-11 15:44:10,764 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:17:04,032 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\models.py changed, reloading.
INFO 2025-10-11 16:17:06,149 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:17:17,052 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 16:17:19,120 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:18:24,207 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\models.py changed, reloading.
INFO 2025-10-11 16:18:26,266 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:20:46,538 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 16:20:48,659 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:20:51,506 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 16:20:53,557 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:21:36,945 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 16:21:39,051 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:22:15,375 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 16:22:17,664 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:24:38,263 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
ERROR 2025-10-11 16:24:49,727 accounts.middleware middleware log_user_activity 193 Error logging user activity: no such table: accounts_useractivity
INFO 2025-10-11 16:24:49,738 django.server basehttp handle_error 81 - Broken pipe from ('127.0.0.1', 53506)
ERROR 2025-10-11 16:24:50,870 accounts.middleware middleware log_user_activity 193 Error logging user activity: no such table: accounts_useractivity
INFO 2025-10-11 16:24:50,879 django.server basehttp log_message 213 "POST /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 302 0
ERROR 2025-10-11 16:24:52,377 django.request log log_response 248 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\dashboard\views.py", line 178, in dashboard
    return render(request, 'dashboard/dashboard_modern.html', context)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'live_monitor' not found. 'live_monitor' is not a valid view function or pattern name.
ERROR 2025-10-11 16:24:52,389 accounts.middleware middleware log_user_activity 193 Error logging user activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:24:52,392 accounts.middleware middleware check_suspicious_activity 303 Error checking suspicious activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:24:52,393 django.server basehttp log_message 213 "GET /dashboard/ HTTP/1.1" 500 306991
INFO 2025-10-11 16:25:34,182 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-11 16:25:34,205 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
INFO 2025-10-11 16:29:25,763 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\urls_activity.py changed, reloading.
INFO 2025-10-11 16:29:28,118 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
ERROR 2025-10-11 16:32:31,527 accounts.middleware middleware log_user_activity 193 Error logging user activity: no such table: accounts_useractivity
INFO 2025-10-11 16:32:31,537 django.server basehttp log_message 213 "GET /dashboard/ HTTP/1.1" 200 87382
ERROR 2025-10-11 16:34:02,371 django.request log log_response 248 Internal Server Error: /accounts/activity-dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: accounts_useractivity

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 130, in activity_dashboard
    total_activities = UserActivity.objects.filter(timestamp__gte=start_time).count()
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: accounts_useractivity
ERROR 2025-10-11 16:34:02,381 accounts.middleware middleware log_user_activity 193 Error logging user activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:34:02,382 accounts.middleware middleware check_suspicious_activity 303 Error checking suspicious activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:34:02,384 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 500 162170
ERROR 2025-10-11 16:36:49,149 django.request log log_response 248 Internal Server Error: /accounts/activity-dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: accounts_useractivity

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 130, in activity_dashboard
    total_activities = UserActivity.objects.filter(timestamp__gte=start_time).count()
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: accounts_useractivity
ERROR 2025-10-11 16:36:49,156 accounts.middleware middleware log_user_activity 193 Error logging user activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:36:49,157 accounts.middleware middleware check_suspicious_activity 303 Error checking suspicious activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:36:49,158 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 500 162307
INFO 2025-10-11 16:50:52,952 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:51:09,092 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
ERROR 2025-10-11 16:51:55,723 django.request log log_response 253 Internal Server Error: /accounts/activity-dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: accounts_useractivity

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 130, in activity_dashboard
    total_activities = UserActivity.objects.filter(timestamp__gte=start_time).count()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: accounts_useractivity
ERROR 2025-10-11 16:51:55,743 accounts.middleware middleware log_user_activity 193 Error logging user activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:51:55,745 accounts.middleware middleware check_suspicious_activity 303 Error checking suspicious activity: no such table: accounts_useractivity
ERROR 2025-10-11 16:51:55,746 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 500 159352
INFO 2025-10-11 16:54:35,260 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 16:55:51,416 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 302 0
INFO 2025-10-11 16:55:51,425 django.server basehttp log_message 213 "GET /accounts/login/?next=/accounts/activity-dashboard/ HTTP/1.1" 200 30083
ERROR 2025-10-11 16:55:59,537 accounts.middleware middleware log_user_activity 193 Error logging user activity: table accounts_useractivity has no column named module
INFO 2025-10-11 16:55:59,553 django.server basehttp log_message 213 "POST /accounts/login/?next=/accounts/activity-dashboard/ HTTP/1.1" 302 0
ERROR 2025-10-11 16:56:00,006 django.request log log_response 253 Internal Server Error: /accounts/activity-dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 190, in activity_dashboard
    return render(request, 'accounts/activity_dashboard.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' if level.activity_level == 'low' else 'warning' if level.activity_level == 'medium' else 'danger'' from ''success' if level.activity_level == 'low' else 'warning' if level.activity_level == 'medium' else 'danger''
ERROR 2025-10-11 16:56:00,027 accounts.middleware middleware log_user_activity 193 Error logging user activity: table accounts_useractivity has no column named module
ERROR 2025-10-11 16:56:00,029 accounts.middleware middleware check_suspicious_activity 303 Error checking suspicious activity: no such column: accounts_useractivity.status_code
ERROR 2025-10-11 16:56:00,030 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 500 305606
ERROR 2025-10-11 17:00:19,864 django.request log log_response 253 Internal Server Error: /accounts/activity-dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: accounts_activityalert.ip_address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 190, in activity_dashboard
    return render(request, 'accounts/activity_dashboard.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 749, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaultfilters.py", line 632, in length
    return len(value)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: accounts_activityalert.ip_address
ERROR 2025-10-11 17:00:19,871 accounts.middleware middleware log_user_activity 193 Error logging user activity: table accounts_useractivity has no column named module
ERROR 2025-10-11 17:00:19,873 accounts.middleware middleware check_suspicious_activity 303 Error checking suspicious activity: no such column: accounts_useractivity.status_code
ERROR 2025-10-11 17:00:19,875 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 500 258064
INFO 2025-10-11 17:02:34,974 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 200 69191
INFO 2025-10-11 17:02:50,305 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 141
INFO 2025-10-11 17:02:50,730 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/?time_range=1h HTTP/1.1" 200 69953
INFO 2025-10-11 17:03:05,922 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 141
INFO 2025-10-11 17:03:19,617 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/?time_range=24h HTTP/1.1" 200 70919
ERROR 2025-10-11 17:03:27,934 django.request log log_response 253 Internal Server Error: /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 427, in session_detail
    return render(request, 'accounts/session_detail.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: accounts/session_detail.html
ERROR 2025-10-11 17:03:27,961 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 500 121767
ERROR 2025-10-11 17:04:55,940 django.request log log_response 253 Internal Server Error: /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 427, in session_detail
    return render(request, 'accounts/session_detail.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' if activity.activity_level == 'low' else 'warning' if activity.activity_level == 'medium' else 'danger' if activity.activity_level == 'high' else 'dark'' from ''success' if activity.activity_level == 'low' else 'warning' if activity.activity_level == 'medium' else 'danger' if activity.activity_level == 'high' else 'dark''
ERROR 2025-10-11 17:04:55,987 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 500 291176
INFO 2025-10-11 17:05:31,473 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 200 88336
INFO 2025-10-11 17:06:01,698 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 200 91386
INFO 2025-10-11 17:06:31,878 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 200 94436
INFO 2025-10-11 17:07:02,156 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 200 97487
INFO 2025-10-11 17:07:32,352 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 200 100539
INFO 2025-10-11 17:07:39,900 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 142
INFO 2025-10-11 17:07:40,012 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/?time_range=24h HTTP/1.1" 200 70925
INFO 2025-10-11 17:07:55,223 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 142
INFO 2025-10-11 17:07:56,145 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 142
INFO 2025-10-11 17:07:56,194 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/?time_range=1h HTTP/1.1" 200 69959
INFO 2025-10-11 17:08:07,546 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 67088
INFO 2025-10-11 17:08:36,783 django.server basehttp log_message 213 "GET /accounts/alerts/?user=2&alert_type=&severity=&is_resolved= HTTP/1.1" 200 66966
INFO 2025-10-11 17:08:42,095 django.server basehttp log_message 213 "GET /accounts/alerts/? HTTP/1.1" 200 67088
INFO 2025-10-11 17:09:03,620 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 200 70925
INFO 2025-10-11 17:13:10,284 django.server basehttp log_message 213 "GET /doctors/ HTTP/1.1" 200 69697
INFO 2025-10-11 17:13:10,548 django.server basehttp log_message 213 "GET /static/img/undraw_profile.svg HTTP/1.1" 200 685
INFO 2025-10-11 17:13:15,449 django.server basehttp log_message 213 "GET /doctors/admin/doctors/ HTTP/1.1" 200 70018
INFO 2025-10-11 17:13:18,576 django.server basehttp log_message 213 "GET /doctors/admin/specializations/ HTTP/1.1" 200 98652
INFO 2025-10-11 17:13:25,278 django.server basehttp log_message 213 "GET /inpatient/admissions/ HTTP/1.1" 200 98561
INFO 2025-10-11 17:13:30,670 django.server basehttp log_message 213 "GET /inpatient/admissions/?page=5 HTTP/1.1" 200 98534
INFO 2025-10-11 17:13:36,702 django.server basehttp log_message 213 "GET /inpatient/admissions/5/ HTTP/1.1" 200 87838
INFO 2025-10-11 17:13:50,862 django.server basehttp log_message 213 "POST /inpatient/admissions/5/payment/ajax-process-outstanding/ HTTP/1.1" 200 247
INFO 2025-10-11 17:14:06,992 django.server basehttp log_message 213 "GET /inpatient/admissions/5/ HTTP/1.1" 200 87027
INFO 2025-10-11 17:14:20,771 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 200 71829
INFO 2025-10-11 17:14:30,480 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 67088
ERROR 2025-10-11 17:16:55,382 django.request log log_response 253 Internal Server Error: /accounts/alerts/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 331, in activity_alerts
    return render(request, 'accounts/activity_alerts.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 191, in __len__
    return len(self.object_list)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1951, in _fetch_all
    self._prefetch_related_objects()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1328, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 2372, in prefetch_related_objects
    raise AttributeError(
    ...<7 lines>...
    )
AttributeError: Cannot find 'related_activities' on ActivityAlert object, 'related_activities' is an invalid parameter to prefetch_related()
ERROR 2025-10-11 17:16:55,409 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 500 203344
INFO 2025-10-11 17:17:22,179 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:17:22,199 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:17:24,819 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 17:17:24,858 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 17:17:34,743 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 134575
INFO 2025-10-11 17:17:40,175 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-11 17:17:40,193 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
INFO 2025-10-11 17:17:59,155 django.server basehttp log_message 213 "GET /accounts/alerts/?user=2&alert_type=&severity=&is_resolved= HTTP/1.1" 200 89186
INFO 2025-10-11 17:18:29,382 django.server basehttp log_message 213 "GET /accounts/alerts/?user=2&alert_type=&severity=&is_resolved= HTTP/1.1" 200 89186
ERROR 2025-10-11 17:18:57,293 django.request log log_response 253 Internal Server Error: /accounts/alerts/1/resolve/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 369, in resolve_alert
    return redirect('accounts:activity_alerts')
           ^^^^^^^^
NameError: name 'redirect' is not defined
ERROR 2025-10-11 17:18:57,326 django.server basehttp log_message 213 "POST /accounts/alerts/1/resolve/ HTTP/1.1" 500 94526
INFO 2025-10-11 17:19:19,084 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:19:19,497 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:19:21,810 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 17:19:22,155 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 17:20:35,314 django.server basehttp log_message 213 "POST /accounts/alerts/1/resolve/ HTTP/1.1" 302 0
INFO 2025-10-11 17:20:35,573 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 134546
INFO 2025-10-11 17:21:01,280 django.server basehttp log_message 213 "GET /accounts/alerts/?user=2&alert_type=&severity=&is_resolved= HTTP/1.1" 200 81618
ERROR 2025-10-11 17:21:10,938 django.request log log_response 253 Internal Server Error: /accounts/activities/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 259, in user_activity_list
    return render(request, 'accounts/user_activity_list.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 191, in __len__
    return len(self.object_list)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1951, in _fetch_all
    self._prefetch_related_objects()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1328, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 2372, in prefetch_related_objects
    raise AttributeError(
    ...<7 lines>...
    )
AttributeError: Cannot find 'alerts' on UserActivity object, 'alerts' is an invalid parameter to prefetch_related()
WARNING 2025-10-11 17:21:10,981 accounts.middleware middleware create_alert 362 Activity alert created: User superuser has 5 failed attempts in the last hour
ERROR 2025-10-11 17:21:10,982 django.server basehttp log_message 213 "GET /accounts/activities/?user=2 HTTP/1.1" 500 213768
INFO 2025-10-11 17:21:33,248 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:21:33,257 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:21:36,059 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 17:22:28,401 django.server basehttp log_message 213 "GET /accounts/activities/?user=2 HTTP/1.1" 200 171656
INFO 2025-10-11 17:23:06,612 django.server basehttp log_message 213 "GET /accounts/activities/42/ HTTP/1.1" 200 76450
INFO 2025-10-11 17:24:01,350 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 200 194902
ERROR 2025-10-11 17:24:27,108 django.request log log_response 253 Internal Server Error: /accounts/sessions/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 405, in user_sessions
    return render(request, 'accounts/user_sessions.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'selectattr'
WARNING 2025-10-11 17:24:27,149 accounts.middleware middleware create_alert 362 Activity alert created: User superuser has 6 failed attempts in the last hour
ERROR 2025-10-11 17:24:27,150 django.server basehttp log_message 213 "GET /accounts/sessions/ HTTP/1.1" 500 304738
INFO 2025-10-11 17:25:24,076 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:25:24,346 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:25:27,194 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 17:25:27,330 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
ERROR 2025-10-11 17:26:04,862 django.request log log_response 253 Internal Server Error: /accounts/sessions/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 411, in user_sessions
    return render(request, 'accounts/user_sessions.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' if session.is_active else 'secondary'' from ''success' if session.is_active else 'secondary''
WARNING 2025-10-11 17:26:04,906 accounts.middleware middleware create_alert 362 Activity alert created: User superuser has 7 failed attempts in the last hour
ERROR 2025-10-11 17:26:04,907 django.server basehttp log_message 213 "GET /accounts/sessions/ HTTP/1.1" 500 363654
ERROR 2025-10-11 17:27:04,048 django.request log log_response 253 Internal Server Error: /accounts/sessions/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 411, in user_sessions
    return render(request, 'accounts/user_sessions.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' if session.is_currently_active else 'secondary'' from ''success' if session.is_currently_active else 'secondary''
WARNING 2025-10-11 17:27:04,113 accounts.middleware middleware create_alert 362 Activity alert created: User superuser has 8 failed attempts in the last hour
ERROR 2025-10-11 17:27:04,114 django.server basehttp log_message 213 "GET /accounts/sessions/ HTTP/1.1" 500 366280
INFO 2025-10-11 17:27:39,912 django.server basehttp log_message 213 "GET /accounts/sessions/ HTTP/1.1" 200 70889
INFO 2025-10-11 17:28:10,137 django.server basehttp log_message 213 "GET /accounts/sessions/ HTTP/1.1" 200 70889
INFO 2025-10-11 17:28:40,280 django.server basehttp log_message 213 "GET /accounts/sessions/ HTTP/1.1" 200 70889
INFO 2025-10-11 17:29:02,862 django.server basehttp log_message 213 "GET /accounts/activities/?user=2 HTTP/1.1" 200 192183
INFO 2025-10-11 17:29:08,462 django.server basehttp log_message 213 "GET /accounts/activities/51/ HTTP/1.1" 200 76486
INFO 2025-10-11 17:29:15,251 django.server basehttp log_message 213 "GET /accounts/activities/?user=2 HTTP/1.1" 200 192174
ERROR 2025-10-11 17:29:22,556 django.request log log_response 253 Internal Server Error: /accounts/live-monitor/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 606, in live_activity_monitor
    return render(request, 'accounts/live_activity_monitor.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'split'
ERROR 2025-10-11 17:29:22,562 django.server basehttp log_message 213 "GET /accounts/live-monitor/ HTTP/1.1" 500 318188
ERROR 2025-10-11 17:29:46,047 django.request log log_response 253 Internal Server Error: /accounts/live-monitor/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 606, in live_activity_monitor
    return render(request, 'accounts/live_activity_monitor.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'split'
ERROR 2025-10-11 17:29:46,052 django.server basehttp log_message 213 "GET /accounts/live-monitor/ HTTP/1.1" 500 318325
INFO 2025-10-11 17:30:35,605 django.server basehttp log_message 213 "GET /accounts/live-monitor/ HTTP/1.1" 200 201711
INFO 2025-10-11 17:30:40,911 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5469
INFO 2025-10-11 17:30:40,951 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:30:45,895 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5437
INFO 2025-10-11 17:30:45,927 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:30:50,904 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5393
INFO 2025-10-11 17:30:50,944 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:30:55,892 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5390
INFO 2025-10-11 17:30:55,934 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:31:00,919 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5372
INFO 2025-10-11 17:31:00,982 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:31:05,899 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5362
INFO 2025-10-11 17:31:05,936 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:31:10,904 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5345
INFO 2025-10-11 17:31:10,940 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:31:16,838 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:31:16,867 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5314
INFO 2025-10-11 17:31:20,887 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5308
INFO 2025-10-11 17:31:20,919 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:31:25,915 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5300
INFO 2025-10-11 17:31:25,951 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:31:30,885 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5290
INFO 2025-10-11 17:31:30,915 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 144
INFO 2025-10-11 17:31:35,896 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5290
INFO 2025-10-11 17:31:35,932 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 144
INFO 2025-10-11 17:31:40,912 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5290
INFO 2025-10-11 17:31:40,971 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 144
INFO 2025-10-11 17:31:45,925 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5290
INFO 2025-10-11 17:31:45,968 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 144
INFO 2025-10-11 17:31:50,915 django.server basehttp log_message 213 "GET /accounts/api/recent-activities/?limit=20 HTTP/1.1" 200 5290
INFO 2025-10-11 17:31:50,946 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 144
INFO 2025-10-11 17:31:55,527 django.server basehttp log_message 213 "GET /accounts/sessions/38twxnjrrinnh8elqhzx2wy2nsyte9ho/ HTTP/1.1" 200 219218
INFO 2025-10-11 17:32:01,520 django.server basehttp log_message 213 "GET /accounts/sessions/ HTTP/1.1" 200 70889
INFO 2025-10-11 17:32:22,567 django.server basehttp log_message 213 "GET /accounts/sessions/?status=active HTTP/1.1" 200 70889
INFO 2025-10-11 17:32:34,467 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 162667
ERROR 2025-10-11 17:32:43,170 django.request log log_response 253 Internal Server Error: /accounts/activity-statistics/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'setvar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 514, in activity_statistics
    return render(request, 'accounts/activity_statistics.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 318: 'setvar', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
WARNING 2025-10-11 17:32:43,218 accounts.middleware middleware create_alert 362 Activity alert created: User superuser has 9 failed attempts in the last hour
ERROR 2025-10-11 17:32:43,219 django.server basehttp log_message 213 "GET /accounts/activity-statistics/ HTTP/1.1" 500 292546
INFO 2025-10-11 17:33:29,978 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:33:30,044 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py changed, reloading.
INFO 2025-10-11 17:33:32,960 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 17:33:33,003 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
ERROR 2025-10-11 17:33:59,530 django.request log log_response 253 Internal Server Error: /accounts/activity-statistics/
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\accounts\activity_views.py", line 520, in activity_statistics
    return render(request, 'accounts/activity_statistics.html', context)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' if total_risk_activities > 100 else 'warning' if total_risk_activities > 50 else 'info'' from ''danger' if total_risk_activities > 100 else 'warning' if total_risk_activities > 50 else 'info''
WARNING 2025-10-11 17:33:59,575 accounts.middleware middleware create_alert 362 Activity alert created: User superuser has 10 failed attempts in the last hour
ERROR 2025-10-11 17:33:59,577 django.server basehttp log_message 213 "GET /accounts/activity-statistics/ HTTP/1.1" 500 287802
INFO 2025-10-11 17:34:38,006 django.server basehttp log_message 213 "GET /accounts/activity-statistics/ HTTP/1.1" 200 89366
INFO 2025-10-11 17:35:16,233 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 177202
INFO 2025-10-11 17:35:40,745 django.server basehttp log_message 213 "GET /accounts/roles/ HTTP/1.1" 200 91754
INFO 2025-10-11 17:35:57,463 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 200 115867
DEBUG 2025-10-11 17:36:06,785 accounts.views views audit_logs 1325 Audit Log ID: 44, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,786 accounts.views views audit_logs 1325 Audit Log ID: 43, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,786 accounts.views views audit_logs 1325 Audit Log ID: 42, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,786 accounts.views views audit_logs 1325 Audit Log ID: 41, Details: {'filters': {'search': 'nazi', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,787 accounts.views views audit_logs 1325 Audit Log ID: 40, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,787 accounts.views views audit_logs 1325 Audit Log ID: 39, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,787 accounts.views views audit_logs 1325 Audit Log ID: 38, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,787 accounts.views views audit_logs 1325 Audit Log ID: 37, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,788 accounts.views views audit_logs 1325 Audit Log ID: 36, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,788 accounts.views views audit_logs 1325 Audit Log ID: 35, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,788 accounts.views views audit_logs 1325 Audit Log ID: 34, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 33, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 32, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 31, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 30, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 29, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 28, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 27, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 26, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 25, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 24, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 23, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 22, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 21, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:36:06,789 accounts.views views audit_logs 1325 Audit Log ID: 20, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
INFO 2025-10-11 17:36:06,854 django.server basehttp log_message 213 "GET /accounts/audit-logs/ HTTP/1.1" 200 143213
INFO 2025-10-11 17:37:10,673 django.server basehttp log_message 213 "GET /accounts/activity-dashboard/ HTTP/1.1" 200 75951
INFO 2025-10-11 17:37:25,922 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 143
INFO 2025-10-11 17:37:31,707 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 177202
INFO 2025-10-11 17:38:02,039 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 177202
INFO 2025-10-11 17:38:37,118 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 177209
INFO 2025-10-11 17:39:05,240 django.server basehttp log_message 213 "GET /accounts/api/system-status/ HTTP/1.1" 200 144
INFO 2025-10-11 17:39:06,618 django.server basehttp handle_error 81 - Broken pipe from ('127.0.0.1', 55298)
DEBUG 2025-10-11 17:39:07,754 accounts.views views audit_logs 1325 Audit Log ID: 44, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,754 accounts.views views audit_logs 1325 Audit Log ID: 43, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,754 accounts.views views audit_logs 1325 Audit Log ID: 42, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,754 accounts.views views audit_logs 1325 Audit Log ID: 41, Details: {'filters': {'search': 'nazi', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,754 accounts.views views audit_logs 1325 Audit Log ID: 40, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 39, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 38, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 37, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 36, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 35, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 34, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 33, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,755 accounts.views views audit_logs 1325 Audit Log ID: 32, Details: {'filters': {'search': '', 'role': '', 'is_active': None}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 31, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 30, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 29, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 28, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 27, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 26, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 25, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 24, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,756 accounts.views views audit_logs 1325 Audit Log ID: 23, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,757 accounts.views views audit_logs 1325 Audit Log ID: 22, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,757 accounts.views views audit_logs 1325 Audit Log ID: 21, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
DEBUG 2025-10-11 17:39:07,757 accounts.views views audit_logs 1325 Audit Log ID: 20, Details: {'filters': {'search': '', 'role': '', 'is_active': ''}}
INFO 2025-10-11 17:39:10,073 django.server basehttp log_message 213 "GET /accounts/audit-logs/ HTTP/1.1" 200 143210
INFO 2025-10-11 17:39:21,192 django.server basehttp log_message 213 "GET /accounts/role-demo/ HTTP/1.1" 200 115864
INFO 2025-10-11 17:39:25,716 django.server basehttp log_message 213 "GET /accounts/alerts/ HTTP/1.1" 200 177209
INFO 2025-10-11 17:39:36,799 django.server basehttp log_message 213 "GET / HTTP/1.1" 200 62834
INFO 2025-10-11 18:02:19,148 django.server basehttp log_message 213 "GET / HTTP/1.1" 200 31713
INFO 2025-10-11 20:06:56,349 django.server basehttp log_message 213 "GET /accounts/login/ HTTP/1.1" 200 30083
INFO 2025-10-11 20:07:09,186 django.server basehttp log_message 213 "POST /accounts/login/ HTTP/1.1" 302 0
INFO 2025-10-11 20:07:10,264 django.server basehttp log_message 213 "GET /dashboard/ HTTP/1.1" 200 86874
INFO 2025-10-11 20:19:26,696 accounts.views views custom_logout_view 161 User superuser (ID: 2) logged out. Reason: manual
INFO 2025-10-11 20:19:26,716 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-11 20:19:26,764 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
INFO 2025-10-11 20:22:47,495 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 20:22:58,520 django.server basehttp log_message 213 "POST /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 302 0
INFO 2025-10-11 20:22:58,645 django.server basehttp log_message 213 "GET /dashboard/ HTTP/1.1" 200 87396
INFO 2025-10-11 20:23:17,732 django.server basehttp log_message 213 "GET /pharmacy/prescriptions/ HTTP/1.1" 200 123796
INFO 2025-10-11 20:23:33,539 django.server basehttp log_message 213 "GET /core/authorization/dashboard/ HTTP/1.1" 200 69959
INFO 2025-10-11 20:23:41,206 django.server basehttp log_message 213 "GET /core/authorization/generate/surgery/2/ HTTP/1.1" 200 72646
INFO 2025-10-11 20:30:51,603 accounts.views views custom_logout_view 161 User superuser (ID: 2) logged out. Reason: manual
INFO 2025-10-11 20:30:51,623 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-11 20:31:19,571 django.server basehttp log_message 213 "GET /core/authorization/generate/surgery/2/ HTTP/1.1" 302 0
INFO 2025-10-11 20:31:19,586 django.server basehttp log_message 213 "GET /accounts/login/?next=/core/authorization/generate/surgery/2/ HTTP/1.1" 200 30083
INFO 2025-10-11 20:31:29,115 django.server basehttp log_message 213 "POST /accounts/login/?next=/core/authorization/generate/surgery/2/ HTTP/1.1" 302 0
INFO 2025-10-11 20:31:29,223 django.server basehttp log_message 213 "GET /core/authorization/generate/surgery/2/ HTTP/1.1" 200 73111
INFO 2025-10-11 20:32:33,312 django.server basehttp log_message 213 "POST /core/authorization/generate/surgery/2/ HTTP/1.1" 302 0
INFO 2025-10-11 20:32:33,427 django.server basehttp log_message 213 "GET /desk-office/authorization-dashboard/ HTTP/1.1" 200 71952
INFO 2025-10-11 20:33:11,434 django.server basehttp log_message 213 "GET /core/authorization/dashboard/ HTTP/1.1" 200 67201
INFO 2025-10-11 20:33:17,642 django.server basehttp log_message 213 "GET /desk-office/authorization-dashboard/ HTTP/1.1" 200 71428
INFO 2025-10-11 20:33:20,780 django.server basehttp log_message 213 "GET /core/authorization/dashboard/ HTTP/1.1" 200 67201
INFO 2025-10-11 20:33:29,304 django.server basehttp log_message 213 "GET /desk-office/authorization-dashboard/ HTTP/1.1" 200 71428
INFO 2025-10-11 20:33:57,361 django.server basehttp log_message 213 "GET /desk-office/generate-code/ HTTP/1.1" 200 61058
INFO 2025-10-11 20:33:57,594 django.server basehttp log_message 213 "GET /static/js/desk_office.js HTTP/1.1" 200 2249
INFO 2025-10-11 20:41:41,134 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\desk_office\authorization_dashboard_views.py changed, reloading.
INFO 2025-10-11 20:41:41,137 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\desk_office\authorization_dashboard_views.py changed, reloading.
INFO 2025-10-11 20:41:41,243 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\desk_office\authorization_dashboard_views.py changed, reloading.
INFO 2025-10-11 20:41:44,602 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 20:41:45,216 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 20:41:45,216 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 20:42:05,155 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\desk_office\authorization_dashboard_views.py changed, reloading.
INFO 2025-10-11 20:42:07,100 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
ERROR 2025-10-11 20:44:10,250 django.request log log_response 248 Internal Server Error: /desk-office/authorization-dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\desk_office\authorization_dashboard_views.py", line 166, in authorization_dashboard
    return render(request, 'desk_office/authorization_dashboard.html', context)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' if code.status == 'active' else 'secondary'' from ''success' if code.status == 'active' else 'secondary''
ERROR 2025-10-11 20:44:10,292 django.server basehttp log_message 213 "GET /desk-office/authorization-dashboard/ HTTP/1.1" 500 345964
INFO 2025-10-11 20:46:44,593 django.server basehttp log_message 213 "GET /desk-office/authorization-dashboard/ HTTP/1.1" 200 78617
ERROR 2025-10-11 20:47:25,039 django.request log log_response 248 Internal Server Error: /desk-office/authorization-dashboard/
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\desk_office\authorization_dashboard_views.py", line 50, in authorization_dashboard
    ).filter(
      ~~~~~~^
        Q(first_name__icontains=search_query) |
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        Q(phone_number__icontains=search_query)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).select_related('user_profile').order_by('first_name', 'last_name')
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1500, in build_filter
    return self._add_q(
           ~~~~~~~~~~~^
        filter_expr,
        ^^^^^^^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\MY_PRODUCTS\HMS\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'nhia_number' into field. Choices are: address, admissions, allergies, anc_records, appointments, authorization_codes, authorizationcode, blood_group, chronic_diseases, city, consultations, country, created_at, current_medications, date_of_birth, dental_records, doctor_reviews, email, emergency_contact_name, emergency_contact_phone, emergency_contact_relation, ent_records, family_planning_records, first_name, gender, gynae_emergency_records, icu_records, id, id_document, insurance_expiry_date, insurance_policy_number, insurance_provider, invoice, invoices, is_active, labor_records, last_name, marital_status, medical_histories, nhia_info, notes, occupation, oncology_records, ophthalmic_records, pack_orders, patient_id, patient_type, phone_number, photo, postal_code, prescriptions, primary_doctor, primary_doctor_id, radiology_orders, referrals, registration_date, retainership_info, scbu_records, state, surgeries, test_requests, updated_at, vitals, waiting_entries, wallet
ERROR 2025-10-11 20:47:25,073 django.server basehttp log_message 213 "POST /desk-office/authorization-dashboard/ HTTP/1.1" 500 156068
INFO 2025-10-11 20:48:48,583 django.utils.autoreload autoreload trigger_reload 265 C:\Users\dell\Desktop\MY_PRODUCTS\HMS\desk_office\authorization_dashboard_views.py changed, reloading.
INFO 2025-10-11 20:48:50,761 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-11 20:49:36,721 django.server basehttp log_message 213 "POST /desk-office/authorization-dashboard/ HTTP/1.1" 200 81544
INFO 2025-10-11 20:50:07,607 django.server basehttp log_message 213 "GET /desk-office/authorization-dashboard/?patient_id=6 HTTP/1.1" 200 84737
INFO 2025-10-11 20:51:04,476 django.server basehttp log_message 213 "GET /core/authorization/dashboard/ HTTP/1.1" 200 67201
INFO 2025-10-11 20:59:05,477 django.server basehttp log_message 213 "GET /core/authorization/dashboard/ HTTP/1.1" 200 67493
INFO 2025-10-11 20:59:41,851 django.server basehttp log_message 213 "GET /desk-office/authorization-dashboard/ HTTP/1.1" 200 78617
INFO 2025-10-11 20:59:47,430 django.server basehttp log_message 213 "POST /desk-office/authorization-dashboard/ HTTP/1.1" 200 80728
INFO 2025-10-12 06:23:10,768 django.server basehttp log_message 213 "POST /accounts/logout/ HTTP/1.1" 200 119
INFO 2025-10-12 06:23:10,804 django.server basehttp log_message 213 "GET /accounts/login/?auto_logout=1&reason=inactivity HTTP/1.1" 200 31940
INFO 2025-10-17 20:11:07,548 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
INFO 2025-10-17 20:12:15,024 django.utils.autoreload autoreload run_with_reloader 667 Watching for file changes with StatReloader
